controllers/game-submissions.controller.js
routes/api/submissions.route.js
services/game-submissions.service.js
src/app/app.module.ts
src/app/submission-list/submission-list.component.css
src/app/submission-list/submission-list.component.html
src/app/submission-list/submission-list.component.ts
src/app/submission.service.ts
src/styles.scss

Begin implementing controls for games selection committee members. This PR includes functional buttons for changing visibility.
Adds a second paginator to the top of the SubmissionListComponent.
Adds better server-side protection for submission API routes.

Committee controls

---

package.json
services/game-submissions.service.js
src/app/profile/profile.component.ts
src/app/submission-form/submission-form.component.html
src/app/submission-list/submission-list.component.html
src/app/submission-list/submission-list.component.ts
src/app/submission.service.ts

Greatly reduces number of requests being made by the client. Other minor bugfixes included.

Serve runner names as part of response object in /api/submissions

---

controllers/game-submissions.controller.js
controllers/speedrun-events.controller.js
models/speedrun-event.model.js
package.json
routes/api.route.js
routes/api/speedrun-events.route.js
services/speedrun-events.service.js
src/app/app.module.ts
src/app/navbar/navbar.component.css
src/app/pre-event-home-page/pre-event-home-page.component.html
src/app/profile/profile.component.html
src/app/profile/profile.component.ts
src/app/speedrun-event.service.spec.ts
src/app/speedrun-event.service.ts
src/app/submission-form/submission-form.component.html
src/app/submission-form/submission-form.component.ts
src/app/submissions-list-page/submissions-list-page.component.css
src/app/submissions-list-page/submissions-list-page.component.html
src/app/submissions-list-page/submissions-list-page.component.scss
src/app/submissions-list-page/submissions-list-page.component.ts
src/styles.scss

Implement a process for admins to open/close game submissions at will.

Advanced submission controls

---

controllers/users.controller.js
models/user.model.js
package.json
routes/api/users.route.js
services/email.service.js
services/users.service.js
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/authentication.service.ts
src/app/login/login.component.html
src/app/password-reset-page/password-reset-page.component.css
src/app/password-reset-page/password-reset-page.component.html
src/app/password-reset-page/password-reset-page.component.spec.ts
src/app/password-reset-page/password-reset-page.component.ts
src/app/signup/signup.component.ts
src/app/user.service.ts
src/app/verify-page/verify-page.component.ts

Adds a password reset feature and addresses some issues related to generating and saving login tokens.

Password reset

---

package.json
src/app/pre-event-home-page/pre-event-home-page.component.html
src/app/pre-event-home-page/pre-event-home-page.component.ts
src/app/registration-page/registration-page.component.html

Also make home page update based on whether registration is open.

Include registration close dates in useful places

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.module.ts
src/app/blog/blog.component.html
src/app/blog/blog.component.scss
src/app/blog/blog.component.spec.ts
src/app/blog/blog.component.ts
src/app/contact/contact.component.html
src/app/contact/contact.component.scss
src/app/contact/contact.component.spec.ts
src/app/contact/contact.component.ts
src/app/footer/footer.component.html
src/app/footer/footer.component.scss
src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.ts
src/app/pre-event-home-page/pre-event-home-page.component.html
src/app/pre-event-home-page/pre-event-home-page.component.scss
src/app/pre-event-home-page/pre-event-home-page.component.ts
src/app/timeline/timeline.component.html
src/app/timeline/timeline.component.scss
src/app/timeline/timeline.component.spec.ts
src/app/timeline/timeline.component.ts

Add blog page
Add announcement blog post
Add timeline to home page
Set website to pre-event mode
Add contact page
Update footer

Update site for pre-2020

---

src/app/navbar/navbar.component.html
src/app/registration-page/registration-page.component.html
src/app/registration-page/registration-page.component.scss
src/app/registration-page/registration-page.component.ts

Update dates and wording for games list and registration period.

Games list registration 2020

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/navbar/navbar.component.html
src/app/volunteer-page/volunteer-page.component.html
src/app/volunteer-page/volunteer-page.component.scss
src/app/volunteer-page/volunteer-page.component.spec.ts
src/app/volunteer-page/volunteer-page.component.ts

Includes navbar link (conditionally)

Add volunteer info page

---

src/app/blog/blog.component.html
src/app/navbar/navbar.component.html
src/app/registration-page/registration-page.component.html

Add prize submission form
Update registration copy

2020 registration games list prizes

---

src/app/footer/footer.component.scss

Add fallback fonts for footer text (for Mac)

---

controllers/users.controller.js
services/email.service.js
services/users.service.js
src/app/user.service.ts
src/app/verify-page/verify-page.component.ts

Changes:
* Check for `verified` field in `UserController.updateUser()`
* Catch more errors during email verification process
* Make errors from `UserService` and `UserController` more descriptive
* Update email addresses in error messages and reply-to fields
* Fix minor linting warnings
* Remove some unused code
Closes #3, #38.

Fix emails and error messages on verify page

---

src/app/blog/blog.component.html

Add statement regarding COVID-19.

New blog post

---

src/app/app.component.html
src/app/blog/blog.component.html
src/app/pre-event-home-page/pre-event-home-page.component.html
src/app/profile/profile.component.html
src/app/profile/profile.component.ts

RPGLB 2020 Cancellation

---

src/app/submissions-list-page/submissions-list-page.component.html

oops, I forgot to update the submissions close date on the submissions page

Update a date for 2023

---

src/app/covid-policy/covid-policy.component.html

Update line on COVID page

---

src/app/volunteer-page/volunteer-page.component.html

Update volunteer copy

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/blog/blog.component.html
src/app/runner-guide/runner-guide.component.css
src/app/runner-guide/runner-guide.component.html
src/app/runner-guide/runner-guide.component.spec.ts
src/app/runner-guide/runner-guide.component.ts

Also add WIP runner guide page.
Closes #134.

Update console policy

---

src/app/registration-page/registration-page.component.html
src/app/registration-page/registration-page.component.ts

Users with new role "skip-payment" will bypass fee.

Add bypass for registration fee

---

src/app/pre-event-home-page/pre-event-home-page.component.html
src/app/submission-form/submission-form.component.html
src/app/submissions-list-page/submissions-list-page.component.html

Ensures dates are displayed in Eastern time zone (both Standard and Daylight, where appropriate). Should consider switching to local time zones eventually.

Fix time zones in date pipes

---

package-lock.json
package.json
src/app/app.module.ts
src/app/contact/contact.component.html
src/app/contact/contact.component.scss
src/app/footer/footer.component.html
src/app/footer/footer.component.scss
src/app/footer/footer.component.ts
src/app/sanitized-html.pipe.ts

The footer needed a little bit of love.

Update footer and contact page with new design and additional links

---

src/app/navbar/navbar.component.html
src/app/navbar/navbar.component.ts

Add store link to navbar and remove some old irrelevant TODO comments.

Add store link

---

src/app/speedrun-event.service.ts

For some reason we weren't doing this explicitly before

Add name and url attributes to cause object in SpeedrunEvent
